### ISSUE TITLE
Pablo.support.png not recognised

### ISSUE THREAD

**Issue by dang2906** [premasagar/pablo#96]
Hi,

I am currently testing pablo to see if it suits my needs. I ran the DataUrl support test on Microsoft Edge (as i have to have it working on all browsers) and this returned a true response. I then tested the Pablo.support.png(function(support){...}); functionality and when this code is hit i get the following error:

Object doesn't support property or method 'png'

This also happens on chrome for me.

Can you help with this? is it a bug or am i missing something?

Many Thanks,

**Comment by premasagar** [comment]
Apologies. The docs are wrong; they'll need updating. Try
`Pablo.support.image.png`

-- 
*Prem Rose*
premasagar.com

**Comment by premasagar** [comment]
Closing, as docs updated
