### ISSUE TITLE
dataUrl for 'jpeg' and 'png' not working in IE11

### ISSUE THREAD

**Issue by simonjboyle** [premasagar/pablo#98]
Running the dataURL example here (http://pablojs.com/api/dataUrl/) in IE11, only the SVG type is returning a dataURL; the other two are blank

**Comment by premasagar** [comment]
Apologies, the docs were incorrect and are now updated. Please use `Pablo.support.image.png` and `Pablo.support.image.jpeg` instead of `Pablo.support.png` and `.jpeg` as it previously said.
